config/routes.rb
Rails.application.routes.draw do
  
  resources :links do
    collection do
      get :search
    end
  end

  post '/links/create_raw' => 'links#create_raw'
  resources :links

end

app/models/link.rb
require "open-uri"

class Link < ActiveRecord::Base
	
	# solr searchability
	searchable do
    text :title, :stored => true
    text :html, :stored => true
    string :URL, :stored => true
  end

  # paperclip attachments
  has_attached_file :screenshot, :styles => { :thumb => "320x240>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :screenshot, :content_type => /\Aimage\/.*\Z/

  def picture_from_url(url)
    self.screenshot = open(url)
  end

  def html_from_url(url)
    self.html = open(url).read
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
# OpenURI
require 'open-uri'



class LinksController < ApplicationController
  
  # skip authenticity
  skip_before_filter :verify_authenticity_token

  before_action :set_link, only: [:show, :edit, :update, :destroy]


  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    # configs
    @splash_host = '68.42.117.7:8050'

    @link = Link.new(link_params)

    # print params
    puts link_params
    
    # hit Splash and get HTML
    url_string = "http://#{@splash_host}/render.html?url=#{link_params['URL']}&wait=1"
    rendered_html =  open(url_string).read
    @link.html = rendered_html

    # load into Nokogiri and extract title
    parsed_html = Nokogiri::HTML(rendered_html)
    title = parsed_html.css('title').text
    if title == ""
      @link.title = "Unknown Title"
    else
      @link.title = title
    end
    
    # hit Splash and get thumbnail
    url_string = "http://#{@splash_host}/render.png?url=#{link_params['URL']}&wait=1&width=320&height=240"
    @link.picture_from_url(url_string)


    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end


  # POST /links/create_raw
  # POST /links/create_raw.json
  def create_raw

    @link = Link.new(link_params)

    # print params
    puts link_params

    # get HTML from saved source
    @link.html_from_url(link_params['html'])
    
    # retrieve thumbnail from URL
    @link.picture_from_url(link_params['screenshot'])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/168.42.117.7:8050
  # PATCH/PUT /links/1.json
  def update
    puts link_params
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /books/search
  # GET /books/search.json
  def search
    @links = Link.search do
      keywords params[:query]
    end.results

    respond_to do |format|
      format.html { render :action => "index" }
      format.json { render :json => @links }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :URL, :html, :screenshot)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>linkPad4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- skeleton framework -->
  <link rel="stylesheet" href="/inc/skeleton/css/normalize.css">
  <link rel="stylesheet" href="/inc/skeleton/css/skeleton.css">

</head>
<body>

	<div class="container">
		<div class="row">
			<div class="twelve columns">
				<%= yield %>
			</div>
		</div>
	</div>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :URL %><br>
    <%= f.text_field :URL %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>



<h1>Listing Links</h1>

<!-- beginnings of search -->
<%= form_tag search_links_path, :method => :get do %>
  <p>
    <%= text_field_tag :query, params[:query] %> <%= submit_tag "Search" %>
  </p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Html</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.title %></td>
        <td><%= link.URL %></td>
        <!-- <td><%= link.html %></td> -->
        <td><%= link_to image_tag(link.screenshot.url(:thumb)), link.screenshot.url(:original) %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.URL %>
</p>

<p>
	<%= image_tag @link.screenshot.url(:thumb) %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>